### ISSUE TITLE
Probelm s instalacijom Dockera

### ISSUE THREAD

**Issue by LGreblo** [larics/mrs_course#4]
## Environment
* OS Version: Ubuntu 20.04
* OS Installation: dual-boot
* Docker or manual installation?:Docker

## Description
* Expected behavior: vjerojatno ispis ključa ili novo polje za unos
* Actual behavior: 
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 46706 (unattended-upgr)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

## Steps to reproduce
sudo apt-get install ca-certificates curl gnupg

## Output
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 46706 (unattended-upgr)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

## Additional context
* ID procesa koji uzrokuje probelm se ne izvodi:
ps aux | grep -i apt
lg         91465  0.0  0.0  11908   660 pts/0    S+   18:10   0:00 grep --color=auto -i apt

**Comment by mkrizmancic** [comment]
Hi @LGreblo. I understand this is a problem related to the installation of the docker engine (and not our custom setup with the simulator). From the output, it looks like you tried to install it while Ubuntu was performing some updates in the background. This is a common issue on Ubuntu.

A simple solution should be to just wait until the update finishes and then try again. If the issue persists, please contact me by email.

**Comment by LGreblo** [comment]
After some persuasion the file that created the problem was updated and installation completed successfully. 

Thank you for your advice.
